name: Core Typecheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  core-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install Pillow dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev freetype-dev # freetype for font support, just in case

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install

      - name: Run Mypy
        working-directory: llama-index-core
        run: uv run -- mypy llama_index
